#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
TERM="xterm-256color"

export LESS="$LESS -FRXK"

# Set the defaut user.
DEFAULT_USER=mneme

setopt HIST_FIND_NO_DUPS

# Init fuck
eval $(thefuck --alias)
eval "$(direnv hook $SHELL)"

nocorrects=('compose' 'init' 'aws' 'json' 'jest')

for cmd in $nocorrects; do
  if ! type $cmd | grep -Fq alias; then
    alias $cmd="nocorrect $cmd"
  fi
done